name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: List directory contents
      run: |
        pwd
        ls -la
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install fastapi uvicorn sqlalchemy pydantic alembic psycopg2-binary python-jose[cryptography] passlib[bcrypt] python-multipart pytest requests
    
    - name: Build check
      run: |
        python -m compileall .
    
    - name: Deploy placeholder
      run: |
        echo "Deployment steps will be added later"