name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: List directory contents
      run: |
        pwd
        ls -la
        echo "Repository contents:"
        find . -type f -name "*.py"
    
    - name: Basic Python check
      run: |
        python --version
        python -c "print('Basic Python check passed')"